networks:
  freqnet:
    driver: bridge
  freqtrade_network:
    driver: bridge
services:
    Test:
      command:
      - trade
      - --config
      - /freqtrade/user_data/config_Test.json
      - --strategy-path
      - /freqtrade/user_data/strategies
      - --strategy
      - FreqaiExampleStrategy
      container_name: Test
      environment:
      - FREQTRADE_CONFIG_FILE=/freqtrade/user_data/config_Test.json
      - FREQTRADE_STRATEGY=FreqaiExampleStrategy
      - FREQTRADE_PAIRLIST=test_pairs.json
      image: freqtradeorg/freqtrade:stable
      networks:
      - freqtrade_network
      ports:
      - 8737:8080
      restart: unless-stopped
      volumes:
      - ./user_data:/freqtrade/user_data
      - ./ichiv1/user_data:/freqtrade/ichiv1_data:ro

    freqtrade_godstra_hyperopt:
      command: |
        -c "pip install ta && echo 'Setting up GodStra hyperopt environment...' && mkdir -p /freqtrade/user_data/data/binance && mkdir -p /freqtrade/user_data/hyperopts && echo 'Downloading data for hyperopt...' && freqtrade download-data --config /freqtrade/user_data/config.json --pairs BTC/USDT ETH/USDT BNB/USDT XRP/USDT ADA/USDT SOL/USDT --timerange 20230101-20240601 --timeframes 12h --exchange binance --verbose && echo 'Starting hyperopt optimization...' && freqtrade hyperopt --hyperopt-loss SharpeHyperOptLoss --spaces buy sell roi stoploss --strategy GodStra --timeframe 12h --timerange 20230101-20240401 --epochs 50 --random-state 42 --print-all && echo 'Hyperopt completed! Check the results in the logs above.'"
      container_name: freqtrade_godstra_hyperopt
      entrypoint: /bin/bash
    freqtrade_godstra_trading:
      command: |
        -c "pip install ta && echo 'Starting GodStra trading bot...' && echo 'Using optimized parameters from strategy defaults' && freqtrade trade --config /freqtrade/user_data/config.json --strategy GodStra --db-url sqlite:////freqtrade/user_data/tradesv3_godstra.sqlite --strategy-path /freqtrade/user_data/strategies --verbose"
      container_name: freqtrade_godstra_trading
      entrypoint: /bin/bash
      image: freqtradeorg/freqtrade:stable
      networks:
      - freqnet
      ports:
      - 0.0.0.0:8084:8080
      restart: 'no'
      volumes:
      - userdata_godstra:/freqtrade/user_data
      - ./user_data/config_hyperopt.json:/freqtrade/user_data/config.json
      - ./user_data/strategies/GodStra.py:/freqtrade/user_data/strategies/GodStra.py
  
    test1:
      command:
      - trade
      - --config
      - /freqtrade/user_data/config_test1.json
      - --strategy-path
      - /freqtrade/user_data/strategies
      - --strategy
      - FreqaiExampleStrategy
      container_name: test1
      environment:
      - FREQTRADE_CONFIG_FILE=/freqtrade/user_data/config_test1.json
      - FREQTRADE_STRATEGY=FreqaiExampleStrategy
      - FREQTRADE_PAIRLIST=test_pairs.json
      image: freqtradeorg/freqtrade:stable
      networks:
      - freqtrade_network
      ports:
      - 8686:8080
      restart: unless-stopped
      volumes:
      - ./user_data:/freqtrade/user_data
      - ./ichiv1/user_data:/freqtrade/ichiv1_data:ro
      test2:
        command:
        - trade
        - --config
        - /freqtrade/user_data/config_test2.json
        - --strategy-path
        - /freqtrade/user_data/strategies
        - --strategy
        - FreqaiExampleStrategy
        container_name: test2
        environment:
        - FREQTRADE_CONFIG_FILE=/freqtrade/user_data/config_test2.json
        - FREQTRADE_STRATEGY=FreqaiExampleStrategy
        - FREQTRADE_PAIRLIST=test_pairs.json
        image: freqtradeorg/freqtrade:stable
        networks:
        - freqtrade_network
        ports:
        - 8687:8080
        restart: unless-stopped
        volumes:
        - ./user_data:/freqtrade/user_data
        - ./ichiv1/user_data:/freqtrade/ichiv1_data:ro

    test122:
      image: freqtradeorg/freqtrade:stable
      container_name: test122
      restart: unless-stopped
      volumes:
      - ./user_data:/freqtrade/user_data
      - ./ichiv1/user_data:/freqtrade/ichiv1_data:ro
      command:
      - trade
      - --config
      - /freqtrade/user_data/config_test122.json
      - --strategy-path
      - /freqtrade/user_data/strategies
      - --strategy
      - FreqaiExampleStrategy
      environment:
      - FREQTRADE_CONFIG_FILE=/freqtrade/user_data/config_test122.json
      - FREQTRADE_STRATEGY=FreqaiExampleStrategy
      - FREQTRADE_PAIRLIST=test_pairs.json
      ports:
      - 8286:8080
      networks:
      - freqtrade_network

volumes:
  userdata_OG_Catboost: null
  userdata_OG_LightGBM: null
  userdata_OG_LightGBM_Inverted: null
  userdata_classification: null
  userdata_filterEMA: null
