services:
    freqtrade:
      image: freqtradeorg/freqtrade:stable_freqaitorch
      restart: unless-stopped
      container_name: freqtrade
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
      volumes:
        - ./freqtrade/user_data/config_freqai.example.json:/freqtrade/user_data/config.json
        - ./freqtrade/user_data/strategies/FreQaiExampleStrategy.py:/freqtrade/user_data/strategies/FreQaiExampleStrategy.py
      command: >
        trade
        --config /freqtrade/user_data/config.json
        --strategy FreqaiExampleStrategy
        --freqaimodel LightGBMRegressor
        --strategy-path /freqtrade/user_data/strategies
      ports:
        - "0.0.0.0:8080:8080"

    # tensorboard:
    #     image: freqtradeorg/freqtrade:stable_freqaitorch
    #     container_name: tensorboard
    #     volumes:
    #       - ./freqtrade/ichiv1/user_data:/freqtrade/user_data
    #     #network_mode: "host"
    #     ports:
    #       - "9060:9060"
    #     # Default command used when running `docker compose up` --bind_all
    #     entrypoint: tensorboard
    #     command: >
    #       --bind_all
    #       --port 9060
    #       --logdir /freqtrade/user_data/models

    # plot:
    #   image: freqtradeorg/freqtrade:stable_plot
    #   container_name: freqtrade_plot
    #   volumes:
    #     - ./freqtrade/ichiv1/user_data:/freqtrade/user_data
    #   # Expose api on port 8080 (localhost only)
    #   # Please read the https://www.freqtrade.io/en/stable/rest-api/ documentation
    #   # before enabling this.
    #   ports:
    #     - "127.0.0.1:8082:8080"
    #   # Default command used when running `docker compose up`
    #   command: >
    #     trade
    #     --logfile /freqtrade/user_data/logs/freqtrade.log
    #     --db-url sqlite:////freqtrade/user_data/tradesv3.sqlite
    #     --config /freqtrade/user_data/config_freqai.json
    #     --strategy-path /freqtrade/user_data/strategies
    #     --strategy ichiv1



